/**
 * Ebook Agent Module — Niche & Sub-Niche Data
 *
 * Predefined categories and sub-niches for the dropdown selectors.
 * Users can also enter custom niches.
 */

import type { NicheCategory } from "./types";

export const NICHE_CATEGORIES: NicheCategory[] = [
  {
    id: "health-wellness",
    name: "Health & Wellness",
    description: "Diet, fitness, mental health, yoga, and holistic wellness",
    subNiches: [
      { id: "keto-diet", name: "Keto Diet", description: "Ketogenic diet plans, recipes, and lifestyle" },
      { id: "intermittent-fasting", name: "Intermittent Fasting", description: "Fasting protocols, schedules, and benefits" },
      { id: "yoga-beginners", name: "Yoga for Beginners", description: "Yoga poses, routines, and flexibility" },
      { id: "mental-health", name: "Mental Health & Mindfulness", description: "Anxiety, depression, meditation, stress relief" },
      { id: "weight-loss", name: "Weight Loss", description: "Sustainable weight loss strategies and plans" },
      { id: "meal-prep", name: "Meal Prep & Planning", description: "Batch cooking, weekly plans, nutrition" },
      { id: "gut-health", name: "Gut Health", description: "Microbiome, probiotics, digestive wellness" },
      { id: "sleep-health", name: "Sleep Optimization", description: "Better sleep, circadian rhythm, insomnia remedies" },
      { id: "plant-based", name: "Plant-Based Living", description: "Vegan/vegetarian diet, recipes, nutrition" },
      { id: "senior-fitness", name: "Fitness for Seniors", description: "Low-impact exercises, mobility, aging well" },
    ],
  },
  {
    id: "personal-finance",
    name: "Personal Finance",
    description: "Saving, investing, budgeting, and building wealth",
    subNiches: [
      { id: "budgeting", name: "Budgeting & Saving", description: "Budget methods, saving strategies, frugal living" },
      { id: "investing-beginners", name: "Investing for Beginners", description: "Stocks, ETFs, index funds, portfolio basics" },
      { id: "crypto-basics", name: "Cryptocurrency Basics", description: "Bitcoin, altcoins, blockchain fundamentals" },
      { id: "debt-free", name: "Debt Freedom", description: "Paying off debt, snowball/avalanche methods" },
      { id: "retirement-planning", name: "Retirement Planning", description: "401k, IRA, pension, early retirement" },
      { id: "side-hustles", name: "Side Hustles", description: "Extra income streams, gig economy, freelancing" },
      { id: "real-estate-investing", name: "Real Estate Investing", description: "Rental properties, flipping, REITs" },
      { id: "financial-literacy", name: "Financial Literacy", description: "Money management basics for beginners" },
      { id: "passive-income", name: "Passive Income", description: "Dividend stocks, rentals, digital products" },
      { id: "fire-movement", name: "FIRE Movement", description: "Financial independence, retire early" },
    ],
  },
  {
    id: "self-help",
    name: "Self-Help & Productivity",
    description: "Personal development, habits, motivation, and productivity",
    subNiches: [
      { id: "habit-building", name: "Habit Building", description: "Atomic habits, routine design, behavior change" },
      { id: "productivity", name: "Productivity Systems", description: "GTD, time blocking, focus techniques" },
      { id: "motivation", name: "Motivation & Discipline", description: "Self-discipline, consistency, goal setting" },
      { id: "morning-routine", name: "Morning Routines", description: "Morning habits, journaling, exercise" },
      { id: "minimalism", name: "Minimalism", description: "Decluttering, simple living, essentialism" },
      { id: "confidence", name: "Confidence & Self-Esteem", description: "Imposter syndrome, self-worth, assertiveness" },
      { id: "procrastination", name: "Overcoming Procrastination", description: "Focus, action-taking, time management" },
      { id: "journaling", name: "Journaling & Reflection", description: "Gratitude journaling, self-discovery prompts" },
      { id: "emotional-intelligence", name: "Emotional Intelligence", description: "EQ, empathy, self-awareness, social skills" },
      { id: "stoicism", name: "Stoicism & Philosophy", description: "Ancient wisdom, resilience, inner peace" },
    ],
  },
  {
    id: "business-entrepreneurship",
    name: "Business & Entrepreneurship",
    description: "Startups, marketing, freelancing, and business growth",
    subNiches: [
      { id: "startup-basics", name: "Startup Fundamentals", description: "Idea validation, MVP, lean startup" },
      { id: "digital-marketing", name: "Digital Marketing", description: "SEO, social media, email marketing, content" },
      { id: "freelancing", name: "Freelancing", description: "Getting clients, pricing, portfolio building" },
      { id: "ecommerce", name: "E-commerce", description: "Dropshipping, Shopify, online store setup" },
      { id: "social-media-growth", name: "Social Media Growth", description: "Building audience, content strategy, engagement" },
      { id: "email-marketing", name: "Email Marketing", description: "List building, funnels, newsletters" },
      { id: "content-creation", name: "Content Creation", description: "Blogging, YouTube, podcasting" },
      { id: "saas", name: "SaaS Business", description: "Software as a service, subscriptions, MRR" },
      { id: "personal-branding", name: "Personal Branding", description: "Authority building, thought leadership" },
      { id: "business-planning", name: "Business Planning", description: "Business models, strategy, operations" },
    ],
  },
  {
    id: "technology",
    name: "Technology & Programming",
    description: "AI, coding, cybersecurity, no-code tools",
    subNiches: [
      { id: "ai-basics", name: "AI & Machine Learning Basics", description: "ChatGPT, AI tools, automation, prompts" },
      { id: "python-programming", name: "Python Programming", description: "Python basics, projects, data science" },
      { id: "web-development", name: "Web Development", description: "HTML, CSS, JavaScript, React, Next.js" },
      { id: "cybersecurity", name: "Cybersecurity", description: "Online safety, privacy, ethical hacking" },
      { id: "no-code", name: "No-Code & Low-Code", description: "Bubble, Webflow, Zapier, automation" },
      { id: "data-science", name: "Data Science", description: "Analytics, visualization, statistics" },
      { id: "cloud-computing", name: "Cloud Computing", description: "AWS, Azure, deployment, DevOps" },
      { id: "prompt-engineering", name: "Prompt Engineering", description: "AI prompts, ChatGPT optimization, LLM usage" },
      { id: "mobile-development", name: "Mobile App Development", description: "React Native, Flutter, app design" },
      { id: "iot-smart-home", name: "IoT & Smart Home", description: "Smart devices, home automation, IoT projects" },
    ],
  },
  {
    id: "education-learning",
    name: "Education & Learning",
    description: "Languages, study skills, online courses",
    subNiches: [
      { id: "language-learning", name: "Language Learning", description: "English, Spanish, methods, immersion" },
      { id: "study-skills", name: "Study Skills & Techniques", description: "Spaced repetition, active recall, note-taking" },
      { id: "online-courses", name: "Creating Online Courses", description: "Course design, platform selection, marketing" },
      { id: "speed-reading", name: "Speed Reading", description: "Reading faster, comprehension, retention" },
      { id: "memory-improvement", name: "Memory Improvement", description: "Memory palace, mnemonics, retention" },
      { id: "academic-writing", name: "Academic Writing", description: "Essays, research papers, thesis writing" },
      { id: "test-prep", name: "Test Preparation", description: "SAT, GRE, certifications, exam strategies" },
      { id: "teaching-online", name: "Teaching Online", description: "Virtual classroom, tutoring, engagement" },
    ],
  },
  {
    id: "cooking-recipes",
    name: "Cooking & Recipes",
    description: "Specific diets, quick meals, meal prep, baking",
    subNiches: [
      { id: "quick-meals", name: "Quick & Easy Meals", description: "30-minute meals, one-pot recipes, weeknight dinners" },
      { id: "air-fryer", name: "Air Fryer Recipes", description: "Air fryer cooking, healthy frying, tips" },
      { id: "baking-bread", name: "Bread & Baking", description: "Sourdough, artisan bread, pastry" },
      { id: "smoothies-juices", name: "Smoothies & Juicing", description: "Green smoothies, detox juices, blends" },
      { id: "instant-pot", name: "Instant Pot Cooking", description: "Pressure cooker recipes, one-pot meals" },
      { id: "healthy-meal-prep", name: "Healthy Meal Prep", description: "Weekly prep, batch cooking, containers" },
      { id: "cocktails-drinks", name: "Cocktails & Drinks", description: "Home bartending, mocktails, coffee" },
      { id: "fermentation", name: "Fermentation", description: "Kimchi, kombucha, sauerkraut, pickling" },
    ],
  },
  {
    id: "relationships",
    name: "Relationships & Communication",
    description: "Dating, marriage, parenting, social skills",
    subNiches: [
      { id: "dating", name: "Dating & Attraction", description: "Online dating, first dates, confidence" },
      { id: "marriage", name: "Marriage & Partnership", description: "Communication, conflict resolution, intimacy" },
      { id: "parenting", name: "Parenting", description: "Toddler discipline, teenage years, bonding" },
      { id: "communication-skills", name: "Communication Skills", description: "Active listening, assertiveness, persuasion" },
      { id: "boundaries", name: "Setting Boundaries", description: "Saying no, self-respect, healthy limits" },
      { id: "social-skills", name: "Social Skills", description: "Networking, small talk, making friends" },
      { id: "codependency", name: "Overcoming Codependency", description: "Independence, self-care, healthy attachments" },
    ],
  },
  {
    id: "hobbies-crafts",
    name: "Hobbies & Crafts",
    description: "Photography, painting, gardening, DIY",
    subNiches: [
      { id: "photography", name: "Photography", description: "Camera basics, composition, editing, smartphone" },
      { id: "painting-drawing", name: "Painting & Drawing", description: "Watercolor, acrylic, sketching, digital art" },
      { id: "gardening", name: "Gardening", description: "Vegetable garden, indoor plants, urban gardening" },
      { id: "diy-crafts", name: "DIY & Crafts", description: "Woodworking, knitting, candle making" },
      { id: "genealogy", name: "Genealogy & Family History", description: "Ancestry research, DNA testing, family trees" },
      { id: "board-games", name: "Board Games & Puzzles", description: "Strategy games, game design, puzzle solving" },
    ],
  },
  {
    id: "career-job",
    name: "Career & Job Search",
    description: "Resume, interviews, career change, remote work",
    subNiches: [
      { id: "resume-writing", name: "Resume & CV Writing", description: "ATS-friendly, cover letters, LinkedIn" },
      { id: "interview-skills", name: "Interview Preparation", description: "Behavioral questions, negotiation, mock interviews" },
      { id: "career-change", name: "Career Change", description: "Transition strategies, skill transfer, pivoting" },
      { id: "remote-work", name: "Remote Work", description: "Work from home, productivity, remote tools" },
      { id: "leadership", name: "Leadership & Management", description: "Team management, delegation, decision making" },
      { id: "salary-negotiation", name: "Salary Negotiation", description: "Compensation, raises, market value" },
      { id: "freelance-career", name: "Freelance Career", description: "Client acquisition, pricing, portfolio" },
    ],
  },
];
